[[redirects]]
  from = "/"
  to = "/"
  status = 200
  force = true
  query = {iframe = ":iframe"} # apply this rule for /old-path?path=example
  # NOTE: Each combination of query params will need to be defined in a separate [[redirects]] block. More here: https://www.netlify.com/docs/redirects/#query-params
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"
[[redirects]]
  from = "/test?iframe=yes"
  to = "/"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"
