[[redirects]]
  from = "/?iframe=yes"
  to = "/"
  status = 200
  force = true
  headers = {example = "iframe-header"}

[[redirects]]
  from = "/"
  to = "/"
  status = 200
  force = true
  query = {iframe = ":iframe"}
  headers = {example = "iframe-header"}
